%PSOGSA source code v3.0, Generated by SeyedAli Mirjalili, 2011. 
%Adopted from: S. Mirjalili, S.Z. Mohd Hashim, “A New Hybrid PSOGSA 
%Algorithm for Function Optimization, in IEEE International Conference 
%on Computer and Information Application?ICCIA 2010), China, 2010, pp.374-377.

% clear all
% clc

function [gBest,GlobalBestCost]=Main
N = 30;                        % (sumber of outcomes generates between 0.1 to 0.5 but not equally appart)Size of the swarm " no of objects "
Max_Iteration  = 100;              % Maximum number of "iterations"

Benchmark_Function_ID=23 %(23 means IEEE 3 BUS)Benchmark function ID

[gBestScore,gBest,GlobalBestCost]= FPSOGSA(Benchmark_Function_ID, N, Max_Iteration)

gBest
gBestScore
% plot(GlobalBestCost,'-r')
% title(['\fontsize{12}\bf Benchmark Function: F',num2str(Benchmark_Function_ID)])
% xlabel('\fontsize{12}\bf Iteration');ylabel('\fontsize{12}\bf Fitness(Best-so-far)')
% legend('\fontsize{10}\bf FPSOGSA')
end